version: '3'

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160
      - 4161
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150
      - 4151
  mongo:
     image: mongo:latest
      container_name: "twitter_votes_database"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./_data/mongo:/data/dbgit
      command: mongod --smallfiles --logpath=/dev/null # --quiet
  app:
    build:
      context: .
      dockerfile: ./Docker/TwitterVotes/Dockerfile
    
