version: '3'

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171"
  database:
    image: mariadb
    restart: always
    volumes:
      - ./_data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: c00lpassw0rd
      MYSQL_USER: test
      MYSQL_PASSWORD: test      
      MYSQL_DATABASE: seen_in_twitter_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  seenintwitter-producer:
    image: jaumecapdevila/seen-in-twitter-producer
    environment:
      - SP_TWITTER_KEY=${SP_TWITTER_KEY}
      - SP_TWITTER_SECRET=${SP_TWITTER_SECRET}
      - SP_TWITTER_ACCESSTOKEN=${SP_TWITTER_ACCESSTOKEN}
      - SP_TWITTER_ACCESSSECRET=${SP_TWITTER_ACCESSSECRET}
  seenintwitter-consumer:
    image: jaumecapdevila/seen-in-twitter-consumer
